In [5]:
import numpy as np
import pandas as pd

In [6]:
pip install numpy

Requirement already satisfied: numpy in c:\users\deven\anaconda3\lib\site-packages (1.20.3)
Note: you may need to restart the kernel to use updated packages.

In [7]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

In [8]:
books['Image-URL-M'][1]

'http://images.amazon.com/images/P/0002005018.01.MZZZZZZZ.jpg'

In [9]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [10]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [11]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [12]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [13]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [14]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [15]:
books.duplicated().sum()

0

In [16]:
ratings.duplicated().sum()

0

In [17]:
users.duplicated().sum()

0

In [18]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [19]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [20]:
dataframe = ratings.merge(books,on='ISBN')

In [21]:
dataframe = dataframe[dataframe['Book-Rating']!=0]

In [22]:
dataframe

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
9,50403,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
13,63970,034545104X,8,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031123,276681,1931333246,10,Chorus,Kurt Messick,2003,Dry Bones Press,http://images.amazon.com/images/P/1931333246.0...,http://images.amazon.com/images/P/1931333246.0...,http://images.amazon.com/images/P/1931333246.0...
1031124,276683,0316185922,5,The River Cafe Wine Primer,Joseph Delissio,2000,"Little, Brown",http://images.amazon.com/images/P/0316185922.0...,http://images.amazon.com/images/P/0316185922.0...,http://images.amazon.com/images/P/0316185922.0...
1031127,276688,0312264186,8,You Can't Catch Death: A Daughter's Memoir,Ianthe Brautigan,2001,St. Martin's Press,http://images.amazon.com/images/P/0312264186.0...,http://images.amazon.com/images/P/0312264186.0...,http://images.amazon.com/images/P/0312264186.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [23]:
df_new = dataframe.drop_duplicates(subset=['ISBN', 'Book-Title'])

In [24]:
df_new

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
60,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
178,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
179,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031123,276681,1931333246,10,Chorus,Kurt Messick,2003,Dry Bones Press,http://images.amazon.com/images/P/1931333246.0...,http://images.amazon.com/images/P/1931333246.0...,http://images.amazon.com/images/P/1931333246.0...
1031124,276683,0316185922,5,The River Cafe Wine Primer,Joseph Delissio,2000,"Little, Brown",http://images.amazon.com/images/P/0316185922.0...,http://images.amazon.com/images/P/0316185922.0...,http://images.amazon.com/images/P/0316185922.0...
1031127,276688,0312264186,8,You Can't Catch Death: A Daughter's Memoir,Ianthe Brautigan,2001,St. Martin's Press,http://images.amazon.com/images/P/0312264186.0...,http://images.amazon.com/images/P/0312264186.0...,http://images.amazon.com/images/P/0312264186.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [25]:
author_book_counts = df_new['Book-Author'].value_counts()

In [26]:
df_author = author_book_counts[author_book_counts > 6].index

In [27]:
df_author

Index(['Stephen King', 'Agatha Christie', 'William Shakespeare',
       'Barbara Cartland', 'Nora Roberts', 'Terry Pratchett', 'Isaac Asimov',
       'Charles Dickens', 'Carolyn Keene', 'Ann M. Martin',
       ...
       'Gwynne Forster', 'Dafydd ab Hugh', 'Lawrence Schiller',
       'Gregory J. P. Godek', 'Jill McGown', 'Yasmina Khadra',
       'Elizabeth Enright', 'Tony Kushner', 'Natalie Goldberg',
       'Ellery Queen'],
      dtype='object', length=3427)

In [28]:
filtered_books = df_new[df_new['Book-Author'].isin(df_author)]

In [29]:
filtered_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
181,192101,2080674722,7,Les Particules Elementaires,Michel Houellebecq,1998,Flammarion,http://images.amazon.com/images/P/2080674722.0...,http://images.amazon.com/images/P/2080674722.0...,http://images.amazon.com/images/P/2080674722.0...
183,276744,038550120X,7,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...
370,2288,0425115801,10,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
614,1660,0553561618,6,Dark Paradise,TAMI HOAG,1994,Bantam,http://images.amazon.com/images/P/0553561618.0...,http://images.amazon.com/images/P/0553561618.0...,http://images.amazon.com/images/P/0553561618.0...
...,...,...,...,...,...,...,...,...,...,...
1031046,276579,0307626458,6,Beauty and the Beast (Golden Look-Look Books (...,Michael Teitelbaum,1991,Golden Books,http://images.amazon.com/images/P/0307626458.0...,http://images.amazon.com/images/P/0307626458.0...,http://images.amazon.com/images/P/0307626458.0...
1031051,276579,0590762648,6,"Boom! Zoom! (Hello Reader!, Phonics Fun. Sci-F...",Judith Bauer Stamper,1997,Cartwheel Books (Scholastics),http://images.amazon.com/images/P/0590762648.0...,http://images.amazon.com/images/P/0590762648.0...,http://images.amazon.com/images/P/0590762648.0...
1031108,276680,0671516949,7,A MARRIAGE MADE AT WOODSTOCK,Cathie Pelletier,1995,Washington Square Press,http://images.amazon.com/images/P/0671516949.0...,http://images.amazon.com/images/P/0671516949.0...,http://images.amazon.com/images/P/0671516949.0...
1031109,276680,067179387X,9,The WEIGHT OF WINTER,Cathie Pelletier,1993,Washington Square Press,http://images.amazon.com/images/P/067179387X.0...,http://images.amazon.com/images/P/067179387X.0...,http://images.amazon.com/images/P/067179387X.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [30]:
author_avg_ratings = filtered_books.groupby('Book-Author')['Book-Rating'].mean().sort_values(ascending=False).reset_index()
top_100_authors = author_avg_ratings.head(100)['Book-Author'].tolist()

In [31]:
top_100_authors

['Maki Murakami',
 'Anne Bishop',
 'Wataru Yoshizumi',
 'Takehiko Inoue',
 'Michiro Ueyama',
 'Emanuel Swedenborg',
 'Terri Farley',
 'Kevin Smith',
 'Simon Furman',
 'Daisaku Ikeda',
 'Helene Siegel',
 'Penny Frank',
 'Gerhard Gruitrooy',
 'Neesa Hart',
 'Mitsumasa Anno',
 'Shel Silverstein',
 'Maud Hart Lovelace',
 'Jonathan Pearce',
 'Patricia Thayer',
 'Editors of Phaidon Press',
 'Judd Winick',
 'LURLENE MCDANIEL',
 'Robert Stanek',
 'Ted Smart',
 'Graeme Base',
 'Robert Sabuda',
 'Rick Kirkman',
 'David Attenborough',
 'Tony Abbott',
 'Yu Watase',
 'Soren Kierkegaard',
 'Kathie Denosky',
 'Dougal Dixon',
 'Andrew Lang',
 'Don Coldsmith',
 'Ronda Thompson',
 'Sanami Matoh',
 'Marcia Willett',
 'Mary Oliver',
 'Ken Akamatsu',
 'Winston Graham',
 'A.A. Milne',
 'Raymond Briggs',
 'Clement Clarke Moore',
 'J.R.R. TOLKIEN',
 'Hayao Miyazaki',
 'Walt Disney Company',
 'Jeanie London',
 'B. Kliban',
 'Donna Barr',
 'Arlene Eisenberg',
 'Sarah Strohmeyer',
 'Cheri Huber',
 'Frank Miller',
 'Mary Stanton',
 'H. Jackson, Jr. Brown',
 'Peter Singer',
 'Og Mandino',
 'Jill Murphy',
 'Antoine de Saint-Exupery',
 'Edith Hamilton',
 'Erich KÃ?Â¤stner',
 'Ansel Adams',
 "Bathroom Readers' Institute",
 'Bill Watterson',
 'DR SEUSS',
 'Malcolm X',
 'Hank Hanegraaff',
 'Hubert Selby',
 'Sun Bear',
 'GEORGE R.R. MARTIN',
 'Walter R. Brooks',
 'David Macaulay',
 'Kevin Crossley-Holland',
 'Otfried Preussler',
 'Alexandra Day',
 'Jean De Brunhoff',
 'Max Heindel',
 'David McCullough',
 'Stephen Mitchell',
 'Antoine de Saint-ExupÃ©ry',
 'Susan Branch',
 'Random House',
 'Bradley Trevor Greive',
 'Richard Brautigan',
 'Ellen Emerson White',
 'Edmond Rostand',
 'Richard Thompson',
 'Quino',
 'Jane Belk Moncure',
 'Dr. Seuss',
 'Edgar Rice Burroughs',
 'Molly Ivins',
 'Gary Larson',
 'Stephen W. Hawking',
 'David Baird',
 'Sharon Lee',
 'RAYMOND FEIST',
 'Nina Kiriki Hoffman',
 'Fyodor M. Dostoevsky']

In [32]:
def get_top_books(author):
    author_books = df_new[df_new['Book-Author']==author]
    top_books = author_books.sort_values(by='Book-Rating', ascending=False).head(5)
    top_books_list = top_books.to_dict(orient='records')
    
    print(top_books_list)

In [33]:
get_top_books('Stephen King')

[{'User-ID': 26756, 'ISBN': '0451178599', 'Book-Rating': 10, 'Book-Title': 'Needful Things', 'Book-Author': 'Stephen King', 'Year-Of-Publication': 1993, 'Publisher': 'New Amer Library', 'Image-URL-S': 'http://images.amazon.com/images/P/0451178599.01.THUMBZZZ.jpg', 'Image-URL-M': 'http://images.amazon.com/images/P/0451178599.01.MZZZZZZZ.jpg', 'Image-URL-L': 'http://images.amazon.com/images/P/0451178599.01.LZZZZZZZ.jpg'}, {'User-ID': 13082, 'ISBN': '0451151259', 'Book-Rating': 10, 'Book-Title': 'Eyes of the Dragon', 'Book-Author': 'Stephen King', 'Year-Of-Publication': 1988, 'Publisher': 'Penguin Putnam~mass', 'Image-URL-S': 'http://images.amazon.com/images/P/0451151259.01.THUMBZZZ.jpg', 'Image-URL-M': 'http://images.amazon.com/images/P/0451151259.01.MZZZZZZZ.jpg', 'Image-URL-L': 'http://images.amazon.com/images/P/0451151259.01.LZZZZZZZ.jpg'}, {'User-ID': 86683, 'ISBN': '8484503151', 'Book-Rating': 10, 'Book-Title': 'Un Saco de Huesos', 'Book-Author': 'Stephen King', 'Year-Of-Publication': 2001, 'Publisher': 'Debols!llo', 'Image-URL-S': 'http://images.amazon.com/images/P/8484503151.01.THUMBZZZ.jpg', 'Image-URL-M': 'http://images.amazon.com/images/P/8484503151.01.MZZZZZZZ.jpg', 'Image-URL-L': 'http://images.amazon.com/images/P/8484503151.01.LZZZZZZZ.jpg'}, {'User-ID': 109901, 'ISBN': '0140258590', 'Book-Rating': 10, 'Book-Title': 'Bad Death of Eduard Delacroix (Green Mile S.)', 'Book-Author': 'Stephen King', 'Year-Of-Publication': 1996, 'Publisher': 'Penguin Books Ltd', 'Image-URL-S': 'http://images.amazon.com/images/P/0140258590.01.THUMBZZZ.jpg', 'Image-URL-M': 'http://images.amazon.com/images/P/0140258590.01.MZZZZZZZ.jpg', 'Image-URL-L': 'http://images.amazon.com/images/P/0140258590.01.LZZZZZZZ.jpg'}, {'User-ID': 109901, 'ISBN': '0140258604', 'Book-Rating': 10, 'Book-Title': 'Night Journey (Green Mile S.)', 'Book-Author': 'Stephen King', 'Year-Of-Publication': 1996, 'Publisher': 'Penguin Books Ltd', 'Image-URL-S': 'http://images.amazon.com/images/P/0140258604.01.THUMBZZZ.jpg', 'Image-URL-M': 'http://images.amazon.com/images/P/0140258604.01.MZZZZZZZ.jpg', 'Image-URL-L': 'http://images.amazon.com/images/P/0140258604.01.LZZZZZZZ.jpg'}]

In [34]:
import pickle
pickle.dump(df_new,open('authors.pkl','wb'))

## Popularity Based Recommender System

In [35]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [36]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [37]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [38]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [39]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [40]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_rating']]

In [41]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

## Collaborative Filtering Based Recommender System

In [42]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
padhe_likhe_users = x[x].index

In [43]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]

In [44]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [45]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [46]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [47]:
pt.fillna(0,inplace=True)

In [48]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity_scores = cosine_similarity(pt)

In [51]:
similarity_scores.shape

(706, 706)

In [52]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [53]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg']]

In [54]:
pt.index[545]

"The Handmaid's Tale"

In [55]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [56]:
books.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,0449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [57]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [59]:
pip show numpy

Name: numpy
Version: 1.20.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: c:\users\deven\anaconda3\lib\site-packages
Requires:
Required-by: ydata-profiling, wordcloud, vispy, visions, tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, phik, patsy, pandas, numexpr, numba, mpl-scatter-density, mkl-random, mkl-fft, missingno, matplotlib, imageio, ImageHash, imagecodecs, h5py, glue-vispy-viewers, glue-core, gensim, fast-histogram, echo, daal4py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.